version: '3'

tasks:
  watch:
    desc: Serve the current directory and open in browser
    cmds:
      - npx http-server -o -c-1

  update:
    desc: Add version parameters to changed CSS and JS files in index.html
    cmds:
      - |
        for file in $(git diff --name-only | grep -E '\.(css|js|mjs)$'); do
          timestamp=$(date +%s)
          filename=$(basename "$file")
          echo "Processing file: $filename"
          
          # First attempt to update existing version parameters
          if grep -q "$filename?v=" index.html; then
            perl -i -pe "s|($filename)\?v=[^\"']+|\\1?v=$timestamp|g" index.html
            echo "Updated existing version for $filename to $timestamp"
          else
            # Add version parameter to files without one
            perl -i -pe "s|($filename)([\"'])|\\1?v=$timestamp\\2|g" index.html
            echo "Added new version parameter to $filename: $timestamp"
          fi
        done